# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/DigitalElectronics/VideoMemory/VideoMemory.srcs/sources_1/ip/ClockingWizzard/ClockingWizard.xci
# IP: The module: 'ClockingWizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/DigitalElectronics/VideoMemory/VideoMemory.srcs/sources_1/ip/ClockingWizzard/ClockingWizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/DigitalElectronics/VideoMemory/VideoMemory.srcs/sources_1/ip/ClockingWizzard/ClockingWizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/DigitalElectronics/VideoMemory/VideoMemory.srcs/sources_1/ip/ClockingWizzard/ClockingWizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Projects/DigitalElectronics/VideoMemory/VideoMemory.srcs/sources_1/ip/ClockingWizzard/ClockingWizard.xci
# IP: The module: 'ClockingWizard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/DigitalElectronics/VideoMemory/VideoMemory.srcs/sources_1/ip/ClockingWizzard/ClockingWizard_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/DigitalElectronics/VideoMemory/VideoMemory.srcs/sources_1/ip/ClockingWizzard/ClockingWizard.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/DigitalElectronics/VideoMemory/VideoMemory.srcs/sources_1/ip/ClockingWizzard/ClockingWizard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ClockingWizard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
