# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/DigitalElectronics/project_1/project_1.srcs/sources_1/ip/clockGenerator/clockGenerator.xci
# IP: The module: 'clockGenerator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/DigitalElectronics/project_1/project_1.srcs/sources_1/ip/clockGenerator/clockGenerator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockGenerator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/DigitalElectronics/project_1/project_1.srcs/sources_1/ip/clockGenerator/clockGenerator.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/DigitalElectronics/project_1/project_1.srcs/sources_1/ip/clockGenerator/clockGenerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Projects/DigitalElectronics/project_1/project_1.srcs/sources_1/ip/clockGenerator/clockGenerator.xci
# IP: The module: 'clockGenerator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/DigitalElectronics/project_1/project_1.srcs/sources_1/ip/clockGenerator/clockGenerator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/DigitalElectronics/project_1/project_1.srcs/sources_1/ip/clockGenerator/clockGenerator.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Projects/DigitalElectronics/project_1/project_1.srcs/sources_1/ip/clockGenerator/clockGenerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
