# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/DigitalElectronics/RandomDriehoeken/RandomDriehoeken.srcs/sources_1/new/TriangleFifo/TriangleFifo.xci
# IP: The module: 'TriangleFifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/DigitalElectronics/RandomDriehoeken/RandomDriehoeken.srcs/sources_1/new/TriangleFifo/TriangleFifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'TriangleFifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/DigitalElectronics/RandomDriehoeken/RandomDriehoeken.srcs/sources_1/new/TriangleFifo/TriangleFifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TriangleFifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Projects/DigitalElectronics/RandomDriehoeken/RandomDriehoeken.srcs/sources_1/new/TriangleFifo/TriangleFifo.xci
# IP: The module: 'TriangleFifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/DigitalElectronics/RandomDriehoeken/RandomDriehoeken.srcs/sources_1/new/TriangleFifo/TriangleFifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'TriangleFifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/DigitalElectronics/RandomDriehoeken/RandomDriehoeken.srcs/sources_1/new/TriangleFifo/TriangleFifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TriangleFifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
